package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/marceloaguero/apollo-federation-golang-example/service-profile/graph/data"
	"github.com/marceloaguero/apollo-federation-golang-example/service-profile/graph/model"
)

// Profile is the resolver for the profile field.
func (r *userResolver) Profile(ctx context.Context, obj *model.User) (*model.Profile, error) {
	var res *model.Profile

	for _, p := range data.Profiles {
		if p.UserID == obj.ID {
			res = p
		}
	}
	return res, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
