// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Profile struct {
	UserID string `json:"userId"`
	Age    string `json:"age"`
	Phone  string `json:"phone"`
	Job    string `json:"job"`
}

type User struct {
	ID      string   `json:"id"`
	Profile *Profile `json:"profile"`
}

func (User) IsEntity() {}
